export const appearance = {
  "preferences-form":
    "preferences-form [max-width:760px] grid [grid-template-columns:minmax(0,_1fr)] [gap:var(--space-6)]",
  "preferences-field":
    "preferences-field grid [grid-template-columns:minmax(0,_1fr)] [gap:var(--space-field-label)] min-w-0 [font-size:var(--font-size-label)] [line-height:var(--leading-body)] font-bold [letter-spacing:var(--tracking-label)] [&_strong]:[font-size:var(--font-size-body-large)] [&_strong]:[line-height:var(--leading-body)] [&_strong]:[letter-spacing:var(--tracking-body)]",
  "preferences-actions":
    "preferences-actions flex items-center [gap:var(--space-5)] [@media((max-width:_800px))]:[align-items:stretch] [@media((max-width:_800px))]:flex-col [@media((max-width:_800px))]:[gap:var(--space-4)]",
  "preferences-unsubscribe":
    "preferences-unsubscribe [min-height:var(--size-touch-target)] [padding:0_6px] [border:0] [border-radius:6px] [background:transparent] [color:var(--black)] [cursor:pointer] [font:inherit] [font-size:var(--font-size-control)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] font-bold [transition:color_var(--motion-duration-fast)_var(--motion-ease-standard),_background-color_var(--motion-duration-fast)_var(--motion-ease-standard),_transform_var(--motion-duration-base)_var(--motion-ease-emphasized)] [&:hover]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_transparent)] [&:hover]:[color:var(--deep-blue)] [&:focus-visible]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_transparent)] [&:focus-visible]:[color:var(--deep-blue)] [&:active]:[transform:scale(var(--motion-scale-press))] [&:active]:[transition-duration:var(--motion-duration-press)] [.preferences-actions_&:disabled:hover]:[background:transparent] [.preferences-actions_&:disabled:hover]:[color:inherit] [.preferences-actions_&:disabled:hover]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible):not(:disabled)]:[background:transparent] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible):not(:disabled)]:[color:var(--black)] [@media((max-width:_800px))]:[align-self:flex-start]",
} as const;
