import { containerAppearance } from "@/components/container";

export const appearance = {
  shell: containerAppearance,
  eyebrow:
    "eyebrow [margin:0] flex items-center [gap:10px] [font-family:var(--font-ui)] [font-size:var(--font-size-label)] [line-height:var(--leading-body)] font-bold [letter-spacing:var(--tracking-label)] [text-transform:none] [&_span]:[width:9px] [&_span]:[height:9px] [&_span]:rounded-full [&_span]:[color:var(--interactive-accent)] [&_span]:[background:var(--interactive-accent)] [.cta_&]:[grid-column:1_/_-1] [.cta_&]:[margin:0_0_46px] [.about-closing_>_&]:[grid-column:1_/_-1] [@media((max-width:_800px))]:[.cta_&]:[margin-bottom:0]",
  "section-gray": "section-gray [background:var(--background-gray)]",
  "about-section":
    "about-section [padding:var(--space-section)_0] grid [grid-template-columns:0.9fr_1.1fr] [gap:var(--space-11)] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[padding:var(--space-section)_0] [@media((max-width:_800px))]:[gap:var(--space-heading-content)]",
  "about-section-heading":
    "about-section-heading [align-self:start] grid [gap:34px] [&_h2]:[margin:0] [&_h2]:[font-size:var(--font-size-section-title)] [&_h2]:[line-height:var(--leading-section-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [&_h2]:[color:var(--text-brand)] [&_>_span]:[font-family:var(--font-ui)] [&_>_span]:[font-size:var(--font-size-label)] [&_>_span]:[line-height:var(--leading-body)] [&_>_span]:font-bold [&_>_span]:[letter-spacing:var(--tracking-label)] [&_>_span]:[text-transform:none] [.about-page_&_>_span]:[font-size:var(--font-size-label)] [.about-page_&_>_span]:[line-height:var(--leading-body)] [.about-page_&_>_span]:font-bold [.about-page_&_>_span]:[letter-spacing:var(--tracking-label)] [.about-page_&_>_span]:[text-transform:none] [@media((max-width:_800px))]:[&_h2]:[overflow-wrap:anywhere]",
  "section-number":
    "section-number [margin:0] [color:var(--text-secondary)] [font-family:var(--font-ui)] [font-size:var(--font-size-label)] [line-height:var(--leading-body)] font-bold [letter-spacing:var(--tracking-label)] [text-transform:none] [.intro_&]:[grid-column:1_/_-1]",
  "about-section-label":
    "about-section-label [margin:0] inline-flex [align-items:baseline] [gap:0.35em] [&_>_span:first-child]:[min-width:2ch] [&_>_span:first-child]:[font-variant-numeric:tabular-nums] [@media((max-width:_800px))]:[flex-wrap:wrap]",
  "about-copy":
    "about-copy [&_>_p]:[margin:0] [&_>_p_+_p]:[margin-top:1.35em] [&_>_:first-child]:[margin-top:0] [&_>_:last-child]:[margin-bottom:0] [.about-page_&]:[color:var(--black)] [&_em]:[color:var(--deep-blue)] [&_em]:[font-style:normal] [&_em]:[font-weight:700] [font-size:var(--font-size-body-large)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] font-normal [text-wrap:pretty]",
  "about-boundaries":
    "about-boundaries [.about-page_&_>_section:last-child_ol]:[color:var(--black)] grid [grid-template-columns:1fr_1fr] [gap:1px] [background:var(--black)] [&_>_section]:[min-height:0] [&_>_section]:[padding:var(--space-section)_48px] [&_>_section]:[background:var(--white)] [&_>_section]:flex [&_>_section]:flex-col [&_h2]:[max-width:420px] [&_h2]:[margin:0] [&_h2]:[font-size:var(--font-size-compact-title)] [&_h2]:[line-height:var(--leading-compact-title)] [&_h2]:font-bold [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:[text-transform:none] [&_ol]:[margin:var(--space-related-content)_0_0] [&_ol]:[padding:0] [&_ol]:[list-style:none] [&_ol]:[font-size:var(--font-size-body-large)] [&_ol]:[line-height:var(--leading-body)] [&_ol]:[letter-spacing:var(--tracking-body)] [&_ol]:font-normal [&_ol]:[text-wrap:pretty] [&_li]:grid [&_li]:[grid-template-columns:42px_minmax(0,_1fr)] [&_li]:[align-items:baseline] [&_li]:[gap:14px] [&_li]:[padding:18px_0] [&_li:last-child]:[padding-bottom:0] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[grid-template-rows:auto] [@media((max-width:_800px))]:[&_li_span]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[&_>_section]:[min-height:0] [@media((max-width:_800px))]:[&_>_section]:[padding:var(--space-section)_var(--space-page-gutter)] [@media((max-width:_800px))]:[&_ol]:[margin-top:var(--space-related-content)] [&_>_section:first-child]:[background:var(--surface-inverse)] [&_>_section:first-child]:[color:var(--text-inverse)] [&_>_section:last-child]:[background:var(--surface-highlight)] [&_>_section:last-child]:[color:var(--text-primary)]",
  "about-boundary-number":
    "about-boundary-number [color:var(--medium-blue)] [font-family:var(--font-ui)] [font-variant-numeric:tabular-nums] [font-size:var(--font-size-body-large)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-heading)] font-bold [.about-boundaries_>_section:last-child_&]:[color:var(--deep-blue)] [.about-boundaries_>_section:first-child_&]:[color:var(--text-highlight)]",
  "about-closing":
    "about-closing [&_h2]:[margin:0] [&_h2]:[font-size:var(--font-size-section-title)] [&_h2]:[line-height:var(--leading-section-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [.about-page_&_>_div]:[color:var(--black)] [padding:var(--space-section)_0] grid [grid-template-columns:1fr_1.2fr] [gap:80px] [&_>_div]:[color:var(--black)] [&_>_div]:[font-size:var(--font-size-body-large)] [&_>_div]:[line-height:var(--leading-body)] [&_>_div]:[letter-spacing:var(--tracking-body)] [&_>_div]:font-normal [&_>_div]:[text-wrap:pretty] [&_>_div_p]:[margin:0] [&_>_div_p_+_p]:[margin-top:1.35em] [@media((max-width:_800px))]:[&_h2]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[padding:var(--space-section)_0] [@media((max-width:_800px))]:[gap:var(--space-heading-content)]",
  "reference-note":
    "reference-note [color:var(--text-primary)] [font-size:var(--font-size-body-large)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] font-normal [text-wrap:pretty] [&_>_span]:font-bold",
  "source-link":
    "source-link [color:var(--medium-blue)] font-normal [text-decoration:underline] [text-decoration-thickness:1px] [text-underline-offset:3px] [transition:color_var(--motion-duration-base)_var(--motion-ease-standard)] [&:focus-visible]:[outline:var(--focus-ring-width)_solid_var(--deep-blue)] [&:focus-visible]:[outline-offset:var(--focus-ring-offset)] [&:focus-visible]:[color:var(--interactive-accent)] [&:hover]:[color:var(--interactive-accent)]",
} as const;
