import { containerAppearance } from "@/components/container";

export const appearance = {
  "home-header": "home-header relative [z-index:30] [background:var(--white)]",
  "home-opening": "home-opening [padding-bottom:0] [background:var(--background-gray)]",
  "hero-band": "hero-band [background:var(--background-gray)]",
  hero: "hero [padding:var(--space-section)_0] [&_h1]:[margin:46px_0_68px] [&_h1]:[max-width:1160px] [&_h1]:[font-size:var(--font-size-page-title)] [&_h1]:[line-height:var(--leading-page-title)] [&_h1]:[letter-spacing:var(--tracking-heading)] [&_h1]:font-bold [&_h1]:[text-transform:none] [&_h1]:[text-wrap:balance] [&_h1_em]:[font-style:normal] [&_h1_em]:[color:var(--text-brand)] [@media((max-width:_800px))]:[padding:var(--space-section)_0] [@media((max-width:_800px))]:[&_h1]:[margin:var(--space-7)_0_var(--space-9)] [@media((max-width:_800px))]:[&_h1]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[&_h1]:[letter-spacing:var(--tracking-heading)]",
  shell: containerAppearance,
  eyebrow:
    "eyebrow [margin:0] flex items-center [gap:10px] [font-family:var(--font-ui)] [font-size:var(--font-size-label)] [line-height:var(--leading-body)] font-bold [letter-spacing:var(--tracking-label)] [text-transform:none] [&_span]:[width:9px] [&_span]:[height:9px] [&_span]:rounded-full [&_span]:[color:var(--interactive-accent)] [&_span]:[background:var(--interactive-accent)] [.cta_&]:[grid-column:1_/_-1] [.cta_&]:[margin:0_0_46px] [.about-closing_>_&]:[grid-column:1_/_-1] [@media((max-width:_800px))]:[.cta_&]:[margin-bottom:0]",
  "hero-bottom":
    "hero-bottom grid [grid-template-columns:1fr_1fr] [gap:var(--space-8)] [align-items:end] [&_>_p]:[margin:0] [&_>_p]:[max-width:590px] [&_>_p]:[font-size:var(--font-size-lead)] [&_>_p]:[line-height:var(--leading-body)] [&_>_p]:[letter-spacing:var(--tracking-body)] [&_>_p]:font-normal [&_>_p]:[text-transform:none] [&_>_p]:[text-wrap:pretty] [@media((max-width:_800px))]:[grid-template-columns:1fr]",
  "hero-actions":
    "hero-actions flex items-center [justify-content:flex-end] [gap:28px] [@media((max-width:_800px))]:[justify-content:flex-start] [@media((max-width:_800px))]:[flex-wrap:wrap]",
  "text-link":
    "text-link [display:inline-block] [border-bottom:1px_solid_currentColor] [padding-bottom:4px] [transition:color_var(--motion-duration-base)_var(--motion-ease-standard),_border-color_var(--motion-duration-base)_var(--motion-ease-standard)] [font-size:var(--font-size-control)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] font-bold [.home-page_&]:inline-flex [.home-page_&]:items-center [.home-page_&]:[gap:var(--space-2)] [.home-page_&]:[padding:8px_2px] [.home-page_&]:[border-bottom:0] [.home-page_&]:[transition:color_var(--motion-duration-base)_var(--motion-ease-standard)] [.home-page_&:hover]:[color:var(--deep-blue)] [.home-page_&:focus-visible]:[color:var(--deep-blue)] [.home-page_&:active]:[color:var(--deep-blue)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:hover:not(:active):not(:focus-visible)]:[color:var(--black)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:hover:not(:active):not(:focus-visible)]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:hover:not(:active):not(:focus-visible)]:[box-shadow:none] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:active]:[color:var(--deep-blue)] [&:hover]:[color:var(--interactive-accent)] [&:focus-visible]:[color:var(--interactive-accent)]",
  "arrow-icon":
    "arrow-icon [display:inline-block] [font-family:var(--font-ui)] [font-style:normal] [font-variant-emoji:text] [line-height:1] [.button_&]:[transition:transform_var(--motion-duration-base)_var(--motion-ease-emphasized)] [.button:hover_&]:[transform:translate(3px,_-3px)] [.button:focus-visible_&]:[transform:translate(3px,_-3px)] [.home-page_.text-link_&]:[width:1em] [.home-page_.text-link_&]:[height:1em] [.home-page_.text-link_&]:[flex:none] [.home-page_.text-link_&]:[stroke-width:3] [.home-page_.text-link_&]:[transition:transform_var(--motion-duration-base)_var(--motion-ease-standard)] [.home-page_.allocation-card_>_a_&]:[width:1em] [.home-page_.allocation-card_>_a_&]:[height:1em] [.home-page_.allocation-card_>_a_&]:[flex:none] [.home-page_.allocation-card_>_a_&]:[stroke-width:3] [.home-page_.text-link:hover:not(:active)_&]:[transform:translateX(4px)] [.home-page_.text-link:focus-visible:not(:active)_&]:[transform:translateX(4px)] [.home-page_.text-link:active_&]:[transform:translateX(5px)] [.round-link_&]:[width:32px] [.round-link_&]:[height:32px] [.round-link_&]:font-bold [.round-link_&]:[stroke-width:3] [.allocation-card_>_a_&]:[transition:transform_var(--motion-duration-base)_var(--motion-ease-emphasized)] [.allocation-card_>_a:hover:not(:active)_&]:[transform:translateX(4px)] [.allocation-card_>_a:focus-visible:not(:active)_&]:[transform:translateX(4px)] [.allocation-card_>_a:active_&]:[transform:translateX(5px)] [@media((max-width:_800px))]:font-bold [@media((max-width:_800px))]:[-webkit-text-stroke:0.45px_currentColor] [@media((max-width:_800px))]:[transition:transform_var(--motion-duration-base)_var(--motion-ease-standard)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_.text-link:hover:not(:active):not(:focus-visible)_&]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[.allocation-card_>_a:hover:not(:active):not(:focus-visible)_&]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_.text-link:active_&]:[transform:translateX(5px)] [@media((hover:_none)_and_(pointer:_coarse))]:[.allocation-card_>_a:active_&]:[transform:translateX(5px)] [@media((prefers-reduced-motion:_reduce))]:[.button_&]:[transform:none]! [@media((prefers-reduced-motion:_reduce))]:[.home-page_.text-link_&]:[transform:none]! [@media((prefers-reduced-motion:_reduce))]:[.allocation-card_>_a_&]:[transform:none]!",
  "metric-band":
    "metric-band relative grid grid-cols-3 gap-px bg-black compact:grid-cols-1 compact:gap-0 compact:bg-transparent",
  "date-text":
    "date-text [.performance-page_.page-intro_&]:[margin-left:auto] [.performance-page_.page-intro_&]:[max-width:100%] [font-family:var(--font-ui)] [font-variant-numeric:tabular-nums] [@media((max-width:_800px))]:[.performance-page_.page-intro_&]:[margin-left:0]",
  "home-about":
    "home-about [padding:var(--space-section)_0] grid [grid-template-columns:1.1fr_0.9fr] [gap:var(--space-11)] [align-items:end] [&_h2]:[margin:36px_0_0] [&_h2]:[font-size:var(--font-size-section-title)] [&_h2]:[line-height:var(--leading-section-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [&_h2]:[color:var(--text-brand)] [&_>_div:last-child]:[max-width:580px] [&_>_div:last-child]:[justify-self:end] [&_>_div:last-child_p]:[margin:0_0_40px] [&_>_div:last-child_p]:[color:var(--black)] [&_>_div:last-child_p]:[font-size:var(--font-size-lead)] [&_>_div:last-child_p]:[line-height:var(--leading-body)] [&_>_div:last-child_p]:[letter-spacing:var(--tracking-body)] [&_>_div:last-child_p]:font-normal [@media((max-width:_800px))]:[&_h2]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[padding:var(--space-section)_0] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[gap:var(--space-heading-content)] [@media((max-width:_800px))]:[&_>_div:last-child]:[justify-self:start]",
  "section-number":
    "section-number [margin:0] [color:var(--text-secondary)] [font-family:var(--font-ui)] [font-size:var(--font-size-label)] [line-height:var(--leading-body)] font-bold [letter-spacing:var(--tracking-label)] [text-transform:none] [.intro_&]:[grid-column:1_/_-1]",
  "home-portfolio-section": "home-portfolio-section [background:var(--background-gray)]",
  intro:
    "intro [padding:var(--space-section)_0_var(--space-heading-content)] grid [grid-template-columns:minmax(0,_1.65fr)_minmax(220px,_0.75fr)] [column-gap:var(--space-7)] [align-items:end] [&_h2]:[max-width:860px] [&_h2]:[margin:24px_0_0] [&_h2]:[font-size:var(--font-size-section-title)] [&_h2]:[line-height:var(--leading-section-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [&_h2]:[color:var(--text-brand)] [@media((max-width:_800px))]:[&_h2]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[&_h2]:[padding-right:0] [@media((max-width:_800px))]:[padding:var(--space-section)_0_var(--space-heading-content)] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)]",
  "round-link":
    "round-link [.home-page_&]:[border-color:transparent] [.home-page_&]:[transition:transform_var(--motion-duration-base)_var(--motion-ease-standard),_background-color_var(--motion-duration-base)_var(--motion-ease-standard),_color_var(--motion-duration-base)_var(--motion-ease-standard)] [.home-page_&:hover]:[background:var(--bright-blue)] [.home-page_&:hover]:[color:var(--black)] [.home-page_&:hover]:[transform:scale(var(--motion-scale-hover))] [.home-page_&:focus-visible]:[background:var(--bright-blue)] [.home-page_&:focus-visible]:[color:var(--black)] [.home-page_&:focus-visible]:[transform:scale(var(--motion-scale-hover))] [.home-page_&:active]:[transform:scale(var(--motion-scale-press))] [.home-page_&:active]:[transition-duration:var(--motion-duration-press)] [justify-self:end] [width:76px] [height:76px] [border:1px_solid_var(--black)] rounded-full [background:var(--black)] [color:var(--white)] grid [place-items:center] [transition:transform_var(--motion-duration-base)_var(--motion-ease-emphasized),_background_var(--motion-duration-base)_var(--motion-ease-standard),_color_var(--motion-duration-base)_var(--motion-ease-standard)] [&:hover]:[background:var(--black)] [&:hover]:[color:var(--white)] [&:focus-visible]:[background:var(--black)] [&:focus-visible]:[color:var(--white)] [&:active]:[transform:scale(var(--motion-scale-press))] [@media((max-width:_800px))]:[justify-self:start] [@media((max-width:_800px))]:[margin-top:var(--space-related-content)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:hover:not(:active):not(:focus-visible)]:[background:var(--black)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:hover:not(:active):not(:focus-visible)]:[color:var(--white)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:hover:not(:active):not(:focus-visible)]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:active]:[background:var(--bright-blue)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:active]:[color:var(--black)] [@media((hover:_none)_and_(pointer:_coarse))]:[.home-page_&:active]:[transform:scale(var(--motion-scale-press))]",
  "round-link-arrow":
    "round-link-arrow [@media((max-width:_800px))]:[.home-page_.round-link_&]:[width:32px] [@media((max-width:_800px))]:[.home-page_.round-link_&]:[height:32px] [@media((max-width:_800px))]:[.home-page_.round-link_&]:[stroke-width:3] [@media((max-width:_800px))]:[.home-page_.round-link_&]:[-webkit-text-stroke:0]",
  "holdings-preview":
    "holdings-preview grid [grid-template-columns:minmax(0,_1.65fr)_minmax(220px,_0.75fr)] [gap:var(--space-7)] [padding:0_0_var(--space-section)] [align-items:stretch] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[gap:var(--space-related-content)] [@media((max-width:_800px))]:[padding-bottom:var(--space-section)]",
  "holdings-list": "holdings-list [border-top:1px_solid_var(--black)]",
  "holding-row":
    "holding-row [--holding-row-inset:14px] [min-height:96px] grid [grid-template-columns:56px_1fr_auto] items-center [gap:var(--space-5)] [border-bottom:1px_solid_var(--gray)] [transition:background-color_var(--motion-duration-base)_var(--motion-ease-standard),_padding_var(--motion-duration-base)_var(--motion-ease-emphasized)] [&:hover]:[padding-inline:var(--holding-row-inset)] [&:hover]:[background:color-mix(in_srgb,_var(--bright-blue)_12%,_var(--white))] [&_>_span]:[color:var(--text-secondary)] [&_>_span]:[font-family:var(--font-ui)] [&_>_span]:[font-size:var(--font-size-caption)] [&_>_span]:[line-height:var(--leading-body)] [&_>_span]:font-normal [&_>_span]:[letter-spacing:var(--tracking-body)] [&_>_span]:[font-variant-numeric:tabular-nums] [&_div]:grid [&_div]:[gap:7px] [&_small]:[color:var(--text-secondary)] [&_small]:[font-size:var(--font-size-body)] [&_small]:[line-height:var(--leading-body)] [&_small]:[letter-spacing:var(--tracking-body)] [&_small]:font-normal [&_strong]:[font-size:var(--font-size-compact-title)] [&_strong]:[line-height:var(--leading-compact-title)] [&_strong]:font-bold [&_strong]:[letter-spacing:var(--tracking-heading)] [&_strong]:[text-transform:none] [&_b]:[font-family:var(--font-ui)] [&_b]:[font-size:var(--font-size-data-row)] [&_b]:[line-height:var(--leading-data)] [&_b]:font-normal [&_b]:[letter-spacing:var(--tracking-heading)] [&_b]:[font-variant-numeric:tabular-nums] [@media((max-width:_800px))]:[grid-template-columns:var(--space-6)_minmax(0,_1fr)_auto] [@media((max-width:_800px))]:[gap:var(--space-4)] [@media((max-width:_800px))]:[&_div]:min-w-0 [@media((max-width:_800px))]:[&_small]:[overflow-wrap:anywhere] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active)]:[padding-inline:0] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active)]:[background:transparent] [@media((hover:_none)_and_(pointer:_coarse))]:[&:active]:[padding-inline:var(--holding-row-inset)] [@media((hover:_none)_and_(pointer:_coarse))]:[&:active]:[background:color-mix(in_srgb,_var(--bright-blue)_12%,_var(--white))]",
  "allocation-card":
    "allocation-card [container-type:inline-size] min-w-0 [min-height:100%] [padding:28px] flex flex-col [background:var(--surface-highlight)] [color:var(--text-primary)] [&_>_a]:[margin-top:auto] [&_>_a]:[border-top:1px_solid_rgba(0,_0,_0,_0.18)] [&_>_a]:[padding-top:18px] [&_>_a]:flex [&_>_a]:items-center [&_>_a]:[justify-content:flex-start] [&_>_a]:[gap:var(--space-2)] [&_>_a]:[transition:color_var(--motion-duration-base)_var(--motion-ease-standard)] [&_>_a]:[font-family:var(--font-ui)] [&_>_a]:[font-size:var(--font-size-control)] [&_>_a]:[line-height:var(--leading-body)] [&_>_a]:font-bold [&_>_a:hover]:[color:var(--deep-blue)] [&_>_a:focus-visible]:[color:var(--deep-blue)] [&_>_a:active]:[color:var(--deep-blue)] [&_>_span]:[font-family:var(--font-ui)] [&_>_span]:[font-size:var(--font-size-label)] [&_>_span]:[line-height:var(--leading-body)] [&_>_span]:font-bold [&_>_span]:[letter-spacing:var(--tracking-label)] [&_>_span]:[text-transform:none] [@media((max-width:_800px))]:[padding:var(--space-5)] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_a:hover:not(:active):not(:focus-visible)]:[color:var(--black)] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_a:hover:not(:active):not(:focus-visible)]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_a:hover:not(:active):not(:focus-visible)]:[box-shadow:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_a:active]:[color:var(--deep-blue)]",
  "allocation-visual":
    "allocation-visual [margin:24px_0] grid [grid-template-columns:minmax(190px,_1.35fr)_minmax(130px,_0.65fr)] items-center [gap:var(--space-4)] [@container((max-width:_350px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_1100px)_and_(min-width:_801px))]:[grid-template-columns:1fr] [@media((max-width:_1100px)_and_(min-width:_801px))]:[gap:20px] [@media((max-width:_800px))]:[grid-template-columns:1fr] [@media((max-width:_800px))]:[margin:var(--space-related-content)_0] [@media((max-width:_800px))]:[gap:var(--space-5)]",
  "allocation-ring":
    'allocation-ring relative [isolation:isolate] [width:min(210px,_100%)] [aspect-ratio:1] [justify-self:center] rounded-full grid [place-content:center] [gap:3px] [text-align:center] [&::before]:[content:""] [&::before]:absolute [&::before]:[z-index:-1] [&::before]:[inset:15%] [&::before]:rounded-full [&::before]:[background:var(--bright-blue)] [&_small]:[color:var(--text-secondary)] [&_small]:[font-size:var(--font-size-caption)] [&_small]:[line-height:var(--leading-body)] [&_small]:[letter-spacing:var(--tracking-body)] [&_small]:font-normal [&_>_span]:[font-family:var(--font-ui)] [&_>_span]:[font-size:var(--font-size-data-ring)] [&_>_span]:[line-height:var(--leading-data)] [&_>_span]:font-bold [&_>_span]:[letter-spacing:var(--tracking-heading)] [&_>_span]:[font-variant-numeric:tabular-nums] [@media((max-width:_1100px)_and_(min-width:_801px))]:[width:min(210px,_100%)] [@media((max-width:_800px))]:[width:min(268px,_100%)]',
  "allocation-legend":
    "allocation-legend w-full grid [gap:9px] [font-size:var(--font-size-caption)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] [&_li]:grid [&_li]:[grid-template-columns:10px_minmax(0,_1fr)_auto] [&_li]:items-center [&_li]:[gap:10px] [&_i]:[width:10px] [&_i]:[height:10px] [&_i]:rounded-full [&_i]:[background:var(--deep-blue)] [&_li:nth-child(2)_i]:[background:var(--medium-blue)] [&_li:nth-child(3)_i]:[background:var(--black)] [&_li:nth-child(4)_i]:[border:1px_solid_rgba(0,_0,_0,_0.2)] [&_li:nth-child(4)_i]:[background:var(--white)] [&_li:nth-child(5)_i]:[background:var(--gray)] [&_b]:[font-variant-numeric:tabular-nums]",
  "performance-home":
    "performance-home [padding:var(--space-section)_0] [background:var(--surface-primary)] [color:var(--text-primary)] [@media((max-width:_800px))]:[padding:var(--space-section)_0]",
  "section-heading":
    "section-heading grid [grid-template-columns:1fr_2fr] [align-items:start] [&_h2]:[margin:0] [&_h2]:[font-size:var(--font-size-section-title)] [&_h2]:[line-height:var(--leading-section-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [.returns_&]:block [.returns_&_h2]:[margin-top:var(--space-related-content)] [@media((max-width:_800px))]:[&_h2]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[gap:var(--space-related-content)]",
  "performance-grid":
    "performance-grid grid [grid-template-columns:1.45fr_0.7fr] [gap:80px] [margin-top:var(--space-heading-content)] [align-items:end] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[margin-top:var(--space-heading-content)]",
  "performance-bars":
    "performance-bars [height:360px] flex [align-items:end] [gap:clamp(18px,_4vw,_62px)] [padding:40px_26px_0] [border-left:1px_solid] [border-bottom:1px_solid] [@media((max-width:_800px))]:[height:280px] [@media((max-width:_800px))]:[gap:18px] [@media((max-width:_800px))]:[padding-inline:12px] [.performance-home_&]:[border-color:rgba(0,_0,_0,_0.28)]",
  "year-bar":
    "year-bar [flex:1] grid [align-content:end] [height:100%] [gap:var(--space-4)] [text-align:center] [&_small]:[height:26px] [&_small]:[font-family:var(--font-ui)] [&_small]:[font-size:var(--font-size-caption)] [&_small]:[line-height:var(--leading-body)] [&_small]:font-normal [&_small]:[letter-spacing:var(--tracking-body)] [.performance-home_&_small]:[color:color-mix(in_srgb,_var(--text-primary)_68%,_transparent)]",
  "bar-value":
    "bar-value [min-height:36px] relative [background:var(--interactive-accent)] [.year-bar:nth-child(2)_&]:[background:var(--bright-blue)] [&_span]:absolute [&_span]:[top:-28px] [&_span]:[left:50%] [&_span]:[transform:translateX(-50%)] [&_span]:[white-space:nowrap] [&_span]:[font-family:var(--font-ui)] [&_span]:[font-size:var(--font-size-caption)] [&_span]:[line-height:var(--leading-body)] [&_span]:font-normal [&_span]:[letter-spacing:var(--tracking-body)] [&_span]:[font-variant-numeric:tabular-nums]",
  "performance-copy":
    "performance-copy flex flex-col [align-items:start] [&_p]:[margin:40px_0_12px] [&_p]:[max-width:370px] [&_p]:[font-size:var(--font-size-lead)] [&_p]:[line-height:var(--leading-body)] [&_p]:[letter-spacing:var(--tracking-body)] [&_p]:font-normal [&_p]:[text-transform:none] [&_small]:[font-size:var(--font-size-caption)] [&_small]:[line-height:var(--leading-body)] [&_small]:[letter-spacing:var(--tracking-body)] [&_small]:font-normal [&_>_strong]:[font-family:var(--font-ui)] [&_>_strong]:[font-size:var(--font-size-data-display)] [&_>_strong]:[line-height:var(--leading-data)] [&_>_strong]:[letter-spacing:var(--tracking-heading)] [&_>_strong]:font-bold [&_>_strong]:[font-variant-numeric:tabular-nums] [@media((max-width:_800px))]:[&_>_strong]:[overflow-wrap:anywhere] [.performance-home_&_p]:[color:color-mix(in_srgb,_var(--text-primary)_68%,_transparent)] [.performance-home_&_small]:[color:color-mix(in_srgb,_var(--text-primary)_68%,_transparent)]",
  "memos-home-band": "memos-home-band [background:var(--background-gray)]",
  "memos-home":
    "memos-home [padding:var(--space-section)_0] [@media((max-width:_800px))]:[padding:var(--space-section)_0]",
  "memos-all": "memos-all [display:table] [margin:var(--space-related-content)_0_0_auto]",
  "cta-band":
    "cta-band [.home-page_&]:[background:var(--surface-highlight)] [.home-page_&]:[color:var(--text-primary)]",
  cta: "cta [padding:var(--space-section)_0] grid [grid-template-columns:1fr_auto] [align-items:end] [&_h2]:[margin:0] [&_h2]:[font-size:var(--font-size-section-title)] [&_h2]:[line-height:var(--leading-section-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [@media((max-width:_800px))]:[&_h2]:[overflow-wrap:anywhere] [@media((max-width:_800px))]:[grid-template-columns:minmax(0,_1fr)] [@media((max-width:_800px))]:[gap:var(--space-heading-content)]",
} as const;
