export const appearance = {
  "article-body":
    "article-body [--memo-conclusion-space-before:58px] [--memo-conclusion-space-after:60px] [width:min(1040px,_100%)] [margin-inline:auto] [font-size:var(--font-size-body-large)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] font-normal [text-wrap:pretty] [&_h2]:[margin:0_0_34px] [&_h2]:[font-size:var(--font-size-card-title)] [&_h2]:[line-height:var(--leading-card-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [&_p]:[margin:0] [&_p_+_p]:[margin-top:1.35em] [&_blockquote]:[margin:64px_0] [&_blockquote]:[padding:34px_0] [&_blockquote]:[border-top:3px_solid_var(--medium-blue)] [&_blockquote]:[border-bottom:1px_solid_var(--gray)] [&_blockquote]:[font-size:var(--font-size-card-title)] [&_blockquote]:[line-height:var(--leading-card-title)] [&_blockquote]:[letter-spacing:var(--tracking-heading)] [&_blockquote]:font-bold [&_blockquote]:[text-transform:none] [&_blockquote]:[text-wrap:balance] [@media((max-width:_800px))]:[--memo-conclusion-space-before:49px] [@media((max-width:_800px))]:[--memo-conclusion-space-after:50px] [@media((max-width:_800px))]:[margin-left:0] [@media((max-width:_800px))]:[overflow-wrap:anywhere]",
  "memo-section":
    "memo-section [.memo-section_+_&]:[margin-top:var(--space-section)] [.memo-section_+_&]:[padding-top:var(--space-section-compact)] [.memo-section_+_&]:[border-top:1px_solid_var(--black)] [@media((max-width:_800px))]:[.memo-section_+_&]:[margin-top:var(--space-section)] [@media((max-width:_800px))]:[.memo-section_+_&]:[padding-top:var(--space-section-compact)]",
  "memo-subsection":
    "memo-subsection [margin-top:var(--space-heading-content)] [&_h3]:[margin:0_0_18px] [&_h3]:[font-size:var(--font-size-compact-title)] [&_h3]:[line-height:var(--leading-compact-title)] [&_h3]:[letter-spacing:var(--tracking-heading)] [&_h3]:font-bold [&_h3]:[text-wrap:balance] [.memo-section:has(+_.memo-references)_>_&:last-child]:[margin-top:var(--memo-conclusion-space-before)]",
  "memo-references":
    "memo-references [margin-top:var(--memo-conclusion-space-after)] [padding:var(--space-section-compact)_48px] [background:var(--background-gray)] [&_ol]:[margin:0] [&_ol]:[padding-left:22px] [&_li_+_li]:[margin-top:14px] [@media((max-width:_800px))]:[padding-top:var(--space-section-compact)] [@media((max-width:_800px))]:[padding-inline:var(--space-5)]",
} as const;
