import { containerAppearance } from "@/components/container";

export const appearance = {
  "memo-index":
    "memo-index [padding:var(--space-section)_0] [@media((max-width:_800px))]:[padding-top:var(--space-section)]",
  shell: containerAppearance,
  "memo-disclosure":
    "memo-disclosure [border-top:1px_solid_var(--black)] [border-bottom:1px_solid_var(--black)] [&_>_summary]:grid [&_>_summary]:[grid-template-columns:minmax(0,_1fr)_auto] [&_>_summary]:[gap:22px] [&_>_summary]:items-center [&_>_summary]:[padding:30px_0] [&_>_summary]:[cursor:pointer] [&_>_summary]:[list-style:none] [&_>_summary]:[transition:background-color_var(--motion-duration-base)_var(--motion-ease-standard),_color_var(--motion-duration-base)_var(--motion-ease-standard),_transform_var(--motion-duration-base)_var(--motion-ease-standard)] [&_>_summary]:[font-size:var(--font-size-compact-title)] [&_>_summary]:[line-height:var(--leading-compact-title)] [&_>_summary]:font-bold [&_>_summary]:[letter-spacing:var(--tracking-heading)] [&_>_summary]:[text-transform:none] [&_>_summary:hover]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_var(--white))] [&_>_summary:hover]:[color:var(--deep-blue)] [&_>_summary:focus-visible]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_var(--white))] [&_>_summary:focus-visible]:[color:var(--deep-blue)] [&_>_summary:active]:[transform:scale(var(--motion-scale-press))] [&_>_summary::-webkit-details-marker]:hidden [&_>_summary_>_span:first-child]:[transition:transform_var(--motion-duration-medium)_var(--motion-ease-emphasized)] [&_>_summary:hover_>_span:first-child]:[transform:translateX(var(--motion-offset-summary))] [&_>_summary:focus-visible_>_span:first-child]:[transform:translateX(var(--motion-offset-summary))] [&_>_summary_svg]:[flex:none] [&_>_summary_svg]:[transition:transform_var(--motion-duration-medium)_var(--motion-ease-emphasized)] [&[open]:not([data-closing])_>_summary_svg]:[transform:rotate(180deg)] [@media((max-width:_800px))]:[&_>_summary]:[grid-template-columns:minmax(0,_1fr)_auto] [@media((max-width:_800px))]:[&_>_summary]:[gap:var(--space-4)] [@media((max-width:_800px))]:[&_>_summary]:[padding:var(--space-5)_0] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:hover:not(:active):not(:focus-visible)]:[padding-inline:0] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:hover:not(:active):not(:focus-visible)]:[background:transparent] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:hover:not(:active):not(:focus-visible)]:[color:inherit] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:hover:not(:active):not(:focus-visible)]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:hover:not(:active):not(:focus-visible)]:[box-shadow:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:hover:not(:active):not(:focus-visible)_>_span:first-child]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:active]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_var(--white))] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:active]:[color:var(--deep-blue)] [@media((hover:_none)_and_(pointer:_coarse))]:[&_>_summary:active_>_span:first-child]:[transform:none]",
  "memo-summary-meta":
    "memo-summary-meta inline-flex items-center [gap:12px] [white-space:nowrap] [@media((max-width:_800px))]:[align-self:center] [@media((max-width:_800px))]:[gap:8px]",
  "memo-count": "memo-count [font-variant-numeric:tabular-nums] [color:var(--interactive-accent)]",
  "memo-disclosure-content": "memo-disclosure-content [border-top:1px_solid_var(--gray)]",
  "memo-index-row":
    "memo-index-row grid [grid-template-columns:80px_1fr_160px] [align-items:start] [gap:var(--space-7)] [padding:52px_0] [border-bottom:1px_solid_var(--black)] [transform-origin:center] [transition:background-color_var(--motion-duration-base)_var(--motion-ease-standard),_transform_var(--motion-duration-base)_var(--motion-ease-standard)] [&:hover]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_var(--white))] [&:hover]:[transform:scale(var(--motion-scale-press))] [&:focus-visible]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_var(--white))] [&:focus-visible]:[transform:scale(var(--motion-scale-press))] [&:active]:[transform:scale(var(--motion-scale-press))] [&_>_span]:[color:var(--text-secondary)] [&_>_span]:[font-family:var(--font-ui)] [&_>_span]:[font-size:var(--font-size-caption)] [&_>_span]:[line-height:var(--leading-body)] [&_>_span]:font-normal [&_>_span]:[letter-spacing:var(--tracking-body)] [&_h2]:[margin:16px_0] [&_h2]:[font-size:var(--font-size-card-title)] [&_h2]:[line-height:var(--leading-card-title)] [&_h2]:[letter-spacing:var(--tracking-heading)] [&_h2]:font-bold [&_h2]:[text-transform:none] [&_h2]:[text-wrap:balance] [&_p]:[margin:0] [&_p]:[max-width:670px] [&_p]:[color:var(--text-secondary)] [&_p]:[font-size:var(--font-size-body)] [&_p]:[line-height:var(--leading-body)] [&_p]:[letter-spacing:var(--tracking-body)] [&_p]:font-normal [&_small]:[font-family:var(--font-ui)] [&_small]:[font-size:var(--font-size-caption)] [&_small]:[line-height:var(--leading-body)] [&_small]:font-normal [&_small]:[letter-spacing:var(--tracking-body)] [@media((max-width:_800px))]:[grid-template-columns:44px_1fr] [@media((max-width:_800px))]:[gap:var(--space-4)] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible)]:[background:transparent] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible)]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible)]:[box-shadow:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&:active]:[background:color-mix(in_srgb,_var(--bright-blue)_18%,_var(--white))] [@media((hover:_none)_and_(pointer:_coarse))]:[&:active]:[transform:scale(var(--motion-scale-press))]",
  "memo-meta":
    "memo-meta flex flex-col [align-items:end] [gap:10px] [font-size:var(--font-size-caption)] [line-height:var(--leading-body)] [letter-spacing:var(--tracking-body)] font-normal [font-family:var(--font-ui)] [font-variant-numeric:tabular-nums] [&_b]:[margin-top:auto] [@media((max-width:_800px))]:[grid-column:2] [@media((max-width:_800px))]:[flex-direction:row] [@media((max-width:_800px))]:items-center [@media((max-width:_800px))]:[&_b]:[margin:0_0_0_auto]",
} as const;
