export const appearance = {
  "memo-grid":
    "memo-grid grid [grid-template-columns:repeat(3,_1fr)] [gap:1px] [background:var(--black)] [border:1px_solid_var(--black)] [@media((max-width:_800px))]:[grid-template-columns:1fr]",
  "memo-card":
    "memo-card [min-height:510px] [padding:30px] flex flex-col [transform-origin:center] [transition:transform_var(--motion-duration-base)_var(--motion-ease-standard),_background-color_var(--motion-duration-base)_var(--motion-ease-standard)] [background:var(--surface-primary)] [color:var(--text-primary)] [&:hover]:[background:color-mix(in_srgb,_var(--bright-blue)_22%,_var(--white))] [&:hover]:[transform:scale(var(--motion-scale-press))] [&:focus-visible]:[background:color-mix(in_srgb,_var(--bright-blue)_22%,_var(--white))] [&:focus-visible]:[transform:scale(var(--motion-scale-press))] [&:active]:[background:color-mix(in_srgb,_var(--bright-blue)_28%,_var(--white))] [&:active]:[transform:scale(var(--motion-scale-press))] [&_>_div]:flex [&_>_div]:[justify-content:space-between] [&_>_div]:[gap:20px] [&_>_div]:[font-size:var(--font-size-label)] [&_>_div]:[line-height:var(--leading-body)] [&_>_div]:font-bold [&_>_div]:[letter-spacing:var(--tracking-label)] [&_>_div]:[text-transform:none] [&_h3]:[margin:auto_0_26px] [&_h3]:[font-size:var(--font-size-card-title)] [&_h3]:[line-height:var(--leading-card-title)] [&_h3]:[letter-spacing:var(--tracking-heading)] [&_h3]:font-bold [&_h3]:[text-transform:none] [&_h3]:[text-wrap:balance] [&_p]:[margin:0_0_36px] [&_p]:[color:var(--text-secondary)] [&_p]:[font-size:var(--font-size-body)] [&_p]:[line-height:var(--leading-body)] [&_p]:[letter-spacing:var(--tracking-body)] [&_p]:font-normal [&_>_small]:[padding-top:18px] [&_>_small]:[border-top:1px_solid_var(--gray)] [&_>_small]:[font-size:var(--font-size-caption)] [&_>_small]:[line-height:var(--leading-body)] [&_>_small]:[letter-spacing:var(--tracking-body)] [&_>_small]:font-normal [@media((max-width:_800px))]:[min-height:410px] [@media((max-width:_800px))]:[padding:var(--space-5)] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible)]:[background:var(--white)] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible)]:[transform:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&:hover:not(:active):not(:focus-visible)]:[box-shadow:none] [@media((hover:_none)_and_(pointer:_coarse))]:[&:not(.memo-card-placeholder):active]:[background:color-mix(in_srgb,_var(--bright-blue)_22%,_var(--white))] [@media((hover:_none)_and_(pointer:_coarse))]:[&:not(.memo-card-placeholder):active]:[transform:scale(var(--motion-scale-press))]",
  "memo-card-placeholder":
    "memo-card-placeholder [cursor:default] [&:hover]:[background:var(--white)] [&:hover]:[transform:none] [&:focus-visible]:[background:var(--white)] [&:focus-visible]:[transform:none] [&:active]:[background:var(--white)] [&:active]:[transform:none] [@media((max-width:_800px))]:hidden",
  "date-text":
    "date-text [.performance-page_.page-intro_&]:[margin-left:auto] [.performance-page_.page-intro_&]:[max-width:100%] [font-family:var(--font-ui)] [font-variant-numeric:tabular-nums] [@media((max-width:_800px))]:[.performance-page_.page-intro_&]:[margin-left:0]",
} as const;
